apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-thecodepenguin-com-tls
spec:
  secretName: k8s-thecodepenguin-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s.thecodepenguin.com
  dnsNames:
    - k8s.thecodepenguin.com
    - www.k8s.thecodepenguin.com
