name: Frontend unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build dockerfile
        run: docker build -t razasam007/react-test -f ./client/Dockerfile.dev ./client
      - name: Run tests
        run: docker run -e CI=true razasam007/react-test npm test
